using AppointmentSystem.Data.Data;
using AppointmentSystem.Models.Contracts.CommandRequests.Appointment;
using AppointmentSystem.Models.Models;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace AppointmentSystem.Services.Handlers.AppointmentFeatures
{
    public class BookAppointmentHandler : IRequestHandler<BookAppointmentCommand, bool>
    {
        private readonly ApplicationDbContext _context;

        public BookAppointmentHandler(ApplicationDbContext context) => _context = context;

        public async Task<bool> Handle(BookAppointmentCommand request, CancellationToken cancellationToken)
        {
            // Find the specific slot pre-generated by the admin
            var appointment = await _context.Appointments
                .FirstOrDefaultAsync(a => a.Id == request.AppointmentId, cancellationToken);

            if (appointment == null || appointment?.PatientId != null)
                return false; // Slot doesn't exist or is already booked

            appointment?.PatientId = request.PatientId;
            appointment?.Status = AppointmentStatus.Confirmed; // Or your equivalent status enum

            await _context.SaveChangesAsync(cancellationToken);
            return true;
        }
    }
}